# generated by datamodel-codegen:
#   filename:  shared/value.schema.json
#   timestamp: 2025-04-01T06:11:45+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class Name(Enum):
    windspeed = 'windspeed'
    winddirection = 'winddirection'
    temperature = 'temperature'
    pressure = 'pressure'
    energy = 'energy'


class Unit(Enum):
    mps = 'mps'
    kph = 'kph'
    mph = 'mph'
    rad = 'rad'
    deg = 'deg'
    rev = 'rev'
    field_16segment = '16segment'
    rpm = 'rpm'
    m = 'm'
    cm = 'cm'
    mm = 'mm'
    in_ = 'in'
    ft = 'ft'
    mi = 'mi'
    pa = 'pa'
    hpa = 'hpa'
    psi = 'psi'
    k = 'k'
    c = 'c'
    f = 'f'
    w = 'w'
    kw = 'kw'
    j = 'j'
    wh = 'wh'
    kwh = 'kwh'


class ScalarValue(BaseModel):
    name: Name = Field(
        ..., description='name of the value (e.g., windspeed, temperature, etc.)'
    )
    unit: Unit = Field(..., description='unit of the value')
    value: float = Field(..., description='value')
