# generated by datamodel-codegen:
#   filename:  aggregated-scalar.schema.json
#   timestamp: 2025-03-31T10:52:00+00:00

from __future__ import annotations

from datetime import datetime
from typing import List

from pydantic import BaseModel, Field

from .shared import value_schema


class ScalarDeviceValuesAggregated(BaseModel):
    timestamp: datetime = Field(
        ...,
        description='Timestamp in ISO8601 format (YYYY-MM-DDTHH:mm:ss.ssZ).',
        examples=['1991-03-11T11:40:03.12Z'],
    )
    values: List[value_schema.ScalarValue]
