# generated by datamodel-codegen:
#   filename:  connection.schema.json
#   timestamp: 2026-06-04T13:53:47+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, Field


class Status(Enum):
    online = 'online'
    offline = 'offline'


class Connection(BaseModel):
    timestamp: AwareDatetime = Field(
        ...,
        description='Timestamp in ISO8601 format (YYYY-MM-DDTHH:mm:ss.ssZ).',
        examples=['1991-03-11T11:40:03.12Z'],
    )
    status: Status = Field(..., description='device status')
