# generated by datamodel-codegen:
#   filename:  error.schema.json
#   timestamp: 2025-12-09T13:07:41+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, conint


class Position(BaseModel):
    z: float = Field(..., description='z position')
    x: float = Field(..., description='x position')
    y: float = Field(..., description='y position')


class Error(BaseModel):
    title: str = Field(..., description='short title for the error')
    code: str = Field(..., description='error code')
    description: Optional[str] = Field(
        None, description='long description of the error'
    )
    component: Optional[str] = Field(None, description='source component of error')
    severity: Optional[conint(ge=0, le=4)] = Field(None, description='severity')
    parameters: Optional[Dict[str, Any]] = Field(
        None,
        description='parameters to the current error as key value pairs of any type',
    )
    position: Optional[Position] = Field(
        None, description='position at which the error occurred'
    )


class DeviceErrors(BaseModel):
    timestamp: datetime = Field(
        ...,
        description='Timestamp in ISO8601 format (YYYY-MM-DDTHH:mm:ss.ssZ).',
        examples=['1991-03-11T11:40:03.12Z'],
    )
    activeErrors: Optional[List[Error]] = None
