# generated by datamodel-codegen:
#   filename:  errorlog.schema.json
#   timestamp: 2026-01-21T15:37:26+00:00

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field


class WakuMqttApiErrors(BaseModel):
    timestamp: datetime = Field(
        ...,
        description='Timestamp in ISO8601 format (YYYY-MM-DDTHH:mm:ss.ssZ).',
        examples=['1991-03-11T11:40:03.12Z'],
    )
    sourceMsgID: int = Field(
        ..., description='MQTT ID of message that triggered the error'
    )
    sourceMsgTopic: str = Field(..., description='Topic')
    message: str = Field(..., description='error message')
