# generated by datamodel-codegen:
#   filename:  error.schema.json
#   timestamp: 2026-01-22T11:31:14+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field, conint


class Position(BaseModel):
    z: float = Field(..., description='z position')
    x: float = Field(..., description='x position')
    y: float = Field(..., description='y position')


class Error(BaseModel):
    title: str = Field(..., description='short title for the error')
    code: str = Field(..., description='error code')
    description: str | None = Field(None, description='long description of the error')
    component: str | None = Field(None, description='source component of error')
    severity: conint(ge=0, le=4) | None = Field(None, description='severity')
    parameters: dict[str, Any] | None = Field(
        None,
        description='parameters to the current error as key value pairs of any type',
    )
    position: Position | None = Field(
        None, description='position at which the error occurred'
    )


class DeviceErrors(BaseModel):
    timestamp: datetime = Field(
        ...,
        description='Timestamp in ISO8601 format (YYYY-MM-DDTHH:mm:ss.ssZ).',
        examples=['1991-03-11T11:40:03.12Z'],
    )
    activeErrors: list[Error] | None = None
