# generated by datamodel-codegen:
#   filename:  factsheet.schema.json
#   timestamp: 2026-01-21T15:37:26+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class DeviceFactsheet(BaseModel):
    serial: str = Field(..., description='device identification')
    name: str = Field(..., description='device name')
    manufacturer: str = Field(..., description='manufacturer slug')
    model: str = Field(..., description='model slug')
    version: str | None = Field(None, description='model version')
    deployment: str | None = Field(None, description='deployment name')
