# generated by datamodel-codegen:
#   filename:  order.schema.json
#   timestamp: 2026-06-04T13:53:47+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field


class Status(Enum):
    pending = 'pending'
    started = 'started'
    finished = 'finished'
    cancelled = 'cancelled'
    aborted = 'aborted'


class DeviceOrder(BaseModel):
    timestamp: AwareDatetime = Field(
        ...,
        description='Timestamp in ISO8601 format (YYYY-MM-DDTHH:mm:ss.ssZ).',
        examples=['1991-03-11T11:40:03.12Z'],
    )
    name: str | None = Field(None, description='order name')
    id: str = Field(..., description='unique order identification')
    device_order_id: str | None = Field(
        None, description='device-internal order identification'
    )
    status: Status = Field(..., description='order status')
    parameters: dict[str, Any] | None = Field(
        None,
        description='parameters to the current mission as key value pairs of any type',
    )
