# generated by datamodel-codegen:
#   filename:  values.schema.json
#   timestamp: 2026-06-04T13:53:47+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, Field, conint


class Unit(Enum):
    mps = 'mps'
    kmph = 'kmph'
    mph = 'mph'
    rad = 'rad'
    deg = 'deg'
    rev = 'rev'
    field_16segment = '16segment'
    rpm = 'rpm'
    m = 'm'
    cm = 'cm'
    mm = 'mm'
    in_ = 'in'
    ft = 'ft'
    mi = 'mi'
    pa = 'pa'
    hpa = 'hpa'
    psi = 'psi'
    bar = 'bar'
    k = 'k'
    c = 'c'
    f = 'f'
    w = 'w'
    kw = 'kw'
    j = 'j'
    wh = 'wh'
    kwh = 'kwh'
    percent = 'percent'
    none = 'none'


class Value(BaseModel):
    name: str = Field(
        ..., description='name of the value (e.g., windspeed, temperature, etc.)'
    )
    unit: Unit = Field(..., description='unit of the value')
    value: float = Field(..., description='value')


class DeviceValues(BaseModel):
    timestamp: AwareDatetime = Field(
        ...,
        description='Timestamp in ISO8601 format (YYYY-MM-DDTHH:mm:ss.ssZ).',
        examples=['1991-03-11T11:40:03.12Z'],
    )
    interval: conint(ge=1) | None = Field(
        None,
        description='Interval in seconds. The timestamp will be rounded to the nearest multiple of this interval.',
    )
    values: list[Value]
